#!/usr/local/bin/bash
mkdir ./Parse/bin/
javac -d ./Parse/bin/ -sourcepath ./Parse/src/ ./Parse/src/nlp_parse/main/MainParser1.java
java -classpath ./Parse/bin -Xms3900M -Xmx4096M -XX:-UseGCOverheadLimit nlp_parse.main.MainParser1 $*

